worker_processes  1;
error_log  /www/server/nginx/logs/error.log;
pid        /www/server/nginx/logs/nginx.pid;

events {
    worker_connections  1024;
}

http {
    include       /www/server/nginx/conf/mime.types;
    default_type  application/octet-stream;
    sendfile      on;
    keepalive_timeout  65;

    # 引入站点配置(含 GM 站的 1515 vhost)
    include /www/server/panel/vhost/nginx/*.conf;
}
